version: '3.7'
services:
    app:
      image: co2-calculator-api:latest
      ports:
        - '8000:8000/tcp'
      volumes:
        - ./:/app
    database:
        image: postgres:13.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: