version: '3.7'
services:
    db:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data

#https://github:com/jdaarevalo/docker_postgres_with_data:
#            # copy the sql script to create tables
#            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#            # copy the sql script to fill tables
#            - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
