"""Add countries table indices

Revision ID: 355d6ebd8d5a
Revises: 9223958d9830
Create Date: 2022-02-04 19:45:56.433489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "355d6ebd8d5a"
down_revision = "9223958d9830"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_country_id", table_name="countries")
    op.drop_index("ix_country_iso_code", table_name="countries")
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)
    op.create_index(
        op.f("ix_countries_iso_code"), "countries", ["iso_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_iso_code"), table_name="countries")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.create_index("ix_country_iso_code", "countries", ["iso_code"], unique=False)
    op.create_index("ix_country_id", "countries", ["id"], unique=False)
    # ### end Alembic commands ###
