"""Add events and participants tables

Revision ID: 7bcd10704add
Revises: 9223958d9830
Create Date: 2022-02-04 19:29:48.119686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bcd10704add"
down_revision = "9223958d9830"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "join_mode", sa.Enum("online", "in_person", name="joinmode"), nullable=True
        ),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_participants_id"), "participants", ["id"], unique=False)
    op.drop_index("ix_country_id", table_name="countries")
    op.drop_index("ix_country_iso_code", table_name="countries")
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)
    op.create_index(
        op.f("ix_countries_iso_code"), "countries", ["iso_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_iso_code"), table_name="countries")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.create_index("ix_country_iso_code", "countries", ["iso_code"], unique=False)
    op.create_index("ix_country_id", "countries", ["id"], unique=False)
    op.drop_index(op.f("ix_participants_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
