"""Pluralized country table name

Revision ID: 9223958d9830
Revises: a1e3760a814b
Create Date: 2022-02-04 08:50:14.595884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9223958d9830'
down_revision = 'a1e3760a814b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("country", "countries")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("countries", "country")
    # ### end Alembic commands ###
